name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Create dist folder
      - name: Create dist folder
        run: mkdir -p dist

      # 3. Generate Snake SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: satyajit450
          svg_out_path: dist/github-contribution-grid-snake.svg
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # 4. Deploy to GitHub Pages (output branch)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          publish_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
